actionType: SwitchSubSpineConfig
fields:
  _defaultToRandom:
    type: boolean
    description: default To Random
    values:
      -
        value: false
        display: false
        parse:
          type: literal
          return: false
      -
        value: true
        display: false
        parse:
          type: literal
          return: true
  _index:
    type: number
    description: index
    values:
      -
        value: -1
        display: false
        parse:
          type: literal
          return: -1
      -
        value: 0
        display: false
        parse:
          type: literal
          return: 0
  _indexKey:
    type: string
    description: index Key
    values:
      -
        value: ""
        display: false
        parse:
          type: literal
          return: ""
  _target:
    type: string
    description: target
    values:
      -
        value: BUFF_OWNER
        display: false
        parse:
          type: literal
          return: BUFF_OWNER